import os

from dotenv import load_dotenv

load_dotenv()


AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_RERANK_ENDPOINT = os.getenv("AZURE_RERANK_ENDPOINT")
AZURE_RERANK_API_KEY = os.getenv("AZURE_RERANK_API_KEY")
AZURE_RERANK_DEPLOYMENT = os.getenv("AZURE_RERANK_DEPLOYMENT")
AZURE_CHAT_DEPLOYMENT = os.getenv("AZURE_CHAT_DEPLOYMENT")
AZURE_EMBEDDING_DEPLOYMENT = os.getenv("AZURE_EMBEDDING_DEPLOYMENT")
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION")
AZURE_SEARCH_ENDPOINT = os.getenv("AZURE_SEARCH_ENDPOINT")
AZURE_SEARCH_API_KEY = os.getenv("AZURE_SEARCH_API_KEY")
AZURE_SEARCH_INDEX1 = os.getenv("AZURE_SEARCH_INDEX1", "rag-1789033469043")
AZURE_SEARCH_INDEX2 = os.getenv("AZURE_SEARCH_INDEX2", "rag-1790837277383")

MAX_CONTEXT_TOKENS = int(os.getenv("MAX_CONTEXT_TOKENS", "5000"))

TOP_K = int(os.getenv("TOP_K", "10"))

AZURE_STORAGE_CONNECTION_STRING = os.getenv("AZURE_STORAGE_CONNECTION_STRING")
AZURE_STORAGE_CONTAINER1 = os.getenv("AZURE_STORAGE_CONTAINER1")
AZURE_STORAGE_CONTAINER2 = os.getenv("AZURE_STORAGE_CONTAINER2")
AZURE_SEARCH_INDEXER1 = os.getenv("AZURE_SEARCH_INDEXER1")
AZURE_SEARCH_INDEXER2 = os.getenv("AZURE_SEARCH_INDEXER2")
