# Necessary imports
from azure.core.credentials import AzureKeyCredential
from azure.search.documents import SearchClient
from azure.search.documents.models import VectorizedQuery
from openai import OpenAI
from config import (
    AZURE_SEARCH_ENDPOINT,
    AZURE_SEARCH_API_KEY,
    AZURE_SEARCH_INDEX1,
    AZURE_SEARCH_INDEX2,
    AZURE_OPENAI_ENDPOINT,
    AZURE_OPENAI_API_KEY,
    AZURE_EMBEDDING_DEPLOYMENT,
)

# create the client to talk to your Azure OpenAI resource. This client is to acces the indexer 1 containing a specific document knowledgebase.pdf
search_client1 = SearchClient(
    endpoint=AZURE_SEARCH_ENDPOINT,
    index_name=AZURE_SEARCH_INDEX1,
    credential=AzureKeyCredential(AZURE_SEARCH_API_KEY),
)


# create the client to talk to your Azure OpenAI resource. This client is to acces the indexer 2 containing a specific document knowledgebase2.pdf
search_client2 = SearchClient(
    endpoint=AZURE_SEARCH_ENDPOINT,
    index_name=AZURE_SEARCH_INDEX2,
    credential=AzureKeyCredential(AZURE_SEARCH_API_KEY),
)

# Create the embedding client this is used to talk to your Azure deployed embedding model for embedding the rewritten query and the hypothetical snwer
embedding_client = OpenAI(
    base_url=f"{AZURE_OPENAI_ENDPOINT.rstrip('/')}/openai/v1/",
    api_key=AZURE_OPENAI_API_KEY,
)


# function to generate and return the vector embeddings of the re-written query and the hypothetical answer
def generate_query_embedding(query: str) -> list[float]:
    response = embedding_client.embeddings.create(
        model=AZURE_EMBEDDING_DEPLOYMENT,
        input=query,
        dimensions=1536,
    )

    return response.data[0].embedding


# format the search results into a list to be given to reranker
def format_search_results(results, results2):
    documents = []

    for result in results:
        documents.append(
            {
                "content": result.get("chunk", ""),
                "source": result.get("title", ""),
                "chunk_id": result.get("chunk_id", ""),
                "parent_id": result.get("parent_id", ""),
                "score": result.get("@search.score", 0),
            }
        )
    if results2:
        for result in results2:
            documents.append(
                {
                    "content": result.get("chunk", ""),
                    "source": result.get("title", ""),
                    "chunk_id": result.get("chunk_id", ""),
                    "parent_id": result.get("parent_id", ""),
                    "score": result.get("@search.score", 0),
                }
            )

    return documents


# This function will retrieve relevant candidate documents from the knowledgebase(s) based on the user/rewritten_query  generated by LLM and uses standard vector based retrieval combined with BM25 based keyword search
def hybrid_search(
    query: str,
    rewritten_query,
    decision: str,
    top_k: int = 5,
):
    query_vector = (
        generate_query_embedding(rewritten_query)
        if rewritten_query
        else generate_query_embedding(query)
    )

    # Search the text_vector field for the documents whose vectors are closest to this query vector using K nearest neighbours 
    vector_query = VectorizedQuery(
        vector=query_vector,
        k_nearest_neighbors=top_k,
        fields="text_vector",
        exhaustive=True,
    )
    # retrieve from knowledge base 1/ knowledge base 2/ both based on orchestrator decision
    if decision == "1":
        results2 = None
        search_client = search_client1
    elif decision == "2":
        results2 = None
        search_client = search_client2
    elif decision == "both":
        results2 = search_client2.search(
            search_text=rewritten_query if rewritten_query else query,
            vector_queries=[vector_query],
            top=top_k,
            select=[
                "chunk",
                "title",
                "chunk_id",
                "parent_id",
            ],
        )
        search_client = search_client1

    # retrieve results using BM25 + Vector search
    results = search_client.search(
        search_text=rewritten_query if rewritten_query else query,
        vector_queries=[vector_query],
        top=top_k,
        select=[
            "chunk",
            "title",
            "chunk_id",
            "parent_id",
        ],
    )

    return format_search_results(results, results2)


# This function will retrieve relevant candidate documents from the knowledgebase(s) based on the hypothetical answer generated by LLM and uses standard vector based retrieval for searching
def hyde_retrieval(hyde_answer: str, decision: str, top_k: int = 5):
    hyde_vector = generate_query_embedding(hyde_answer)

    # Search the text_vector field for the documents whose vectors are closest to this query vector using K nearest neighbours
    vector_query = VectorizedQuery(
        vector=hyde_vector,
        k_nearest_neighbors=top_k,
        fields="text_vector",
        exhaustive=True,
    )

    # retrieve from knowledge base 1/ knowledge base 2/ both based on orchestrator decision 
    if decision == "1":
        results2 = None
        search_client = search_client1
    elif decision == "2":
        results2 = None
        search_client = search_client2
    elif decision == "both":
        results2 = search_client2.search(
            vector_queries=[vector_query],
            top=top_k,
            select=[
                "chunk",
                "title",
                "chunk_id",
                "parent_id",
            ],
        )
        search_client = search_client1

    # retrieve results using  Vector search
    results = search_client.search(
        vector_queries=[vector_query],
        top=top_k,
        select=[
            "chunk",
            "title",
            "chunk_id",
            "parent_id",
        ],
    )

    return format_search_results(results, results2)
